Date: 2026-02-04

Owner: Htet Khant Linn

Week: 1

In [ ]:
import numpy as np


## Multiplication

In [ ]:
first_array = np.array([[1,2,3],[4,5,6]])
print(first_array)
print()
A = np.array([[1,2], [3,4]])
B = np.array([[3, 4], [5,7]])
print(A)
print()
print(B)
print()

C = A @ B   # matric multiplication
print(C)
print()

C_element = A * B
print(C_element)
print()

D = np.dot(A, B)    # matrix multiplication
print(D)
print()

E = np.multiply(A, B)
print(E)
print()

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]]

[[3 4]
 [5 7]]

[[13 18]
 [29 40]]

[[ 3  8]
 [15 28]]

[[13 18]
 [29 40]]

[[ 3  8]
 [15 28]]



## Adding and substraction

In [17]:
sum1 = A + B
print("A + B")
print(sum1)
print()

sub1 = A - B
print("A - B")
print(sub1)
print()

sub2 = np.subtract(A, B)
print("np.subtract(A, B)")
print(sub2)
print()

sum2 = np.sum(A)
print("np.sum(A)")
print(sum2)
print()

Borad_num = A + 3
print("A + 3")
print(Borad_num)
print()

board_matrix = np.array([[3,3], [3,3]])

A + B
[[ 4  6]
 [ 8 11]]

A - B
[[-2 -2]
 [-2 -3]]

np.subtract(A, B)
[[-2 -2]
 [-2 -3]]

np.sum(A)
10

A + 3
[[4 5]
 [6 7]]



## Dividing

In [18]:
D = np.divide([12, 14,15], 5)
print("np.divide([12, 14,15], 5)")
print(D)
print()

D_floor = np.floor_divide([12, 14, 15], 5)
print("np.floor_divide([12, 14, 15], 5)")
print(D_floor)
print()

sq = np.sqrt(10)
print("np.sqrt(10)")
print(sq)
print()

np.divide([12, 14,15], 5)
[2.4 2.8 3. ]

np.floor_divide([12, 14, 15], 5)
[2 2 3]

np.sqrt(10)
3.1622776601683795



## Distribution


In [12]:

normal_d = np.random.standard_normal((3,4))

uniform_d = np.random.uniform(1, 12, (3, 4))

# General float No.

np.random.rand()

# Generate IntegerNo.

Random_Int = np.random.randint(1, 50, (2, 5))


zero_matrix = np.zeros((3,4))

one_matrix = np.ones((3,4))

Filter_Ar = np.logical_and(Random_Int>30, Random_Int<50)

Filtered_int = Random_Int[Filter_Ar]

In [13]:
Data_N = np.array([1,3, 4, 5, 7, 9])

Mean_N = np.mean(Data_N)

Median_N = np.median(Data_N)

Var_N = np.var(Data_N)

SD_N = np.std(Data_N)